/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.sheepdog.validation;

import java.io.PrintWriter;
import java.io.StringWriter;

import org.apache.log4j.Logger;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;
import org.farhan.dsl.sheepdog.sheepDog.TestStepContainer;
import org.farhan.dsl.sheepdog.impl.CellImpl;
import org.farhan.dsl.sheepdog.impl.RowImpl;
import org.farhan.dsl.sheepdog.impl.SourceFileRepository;
import org.farhan.dsl.sheepdog.impl.TableImpl;
import org.farhan.dsl.sheepdog.impl.TestProjectImpl;
import org.farhan.dsl.sheepdog.impl.TestStepContainerImpl;
import org.farhan.dsl.sheepdog.impl.TestStepImpl;
import org.farhan.dsl.sheepdog.impl.TestSuiteImpl;
import org.farhan.dsl.sheepdog.sheepDog.Cell;
import org.farhan.dsl.sheepdog.sheepDog.Row;
import org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage;
import org.farhan.dsl.sheepdog.sheepDog.TestSuite;
import org.farhan.dsl.sheepdog.sheepDog.TestStep;
import org.farhan.dsl.sheepdog.sheepDog.Table;
import org.farhan.dsl.issues.*;
import org.farhan.dsl.lang.*;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SheepDogValidator extends AbstractSheepDogValidator {

	private static final Logger logger = Logger.getLogger(SheepDogValidator.class);
	public static final String CELL_NAME = "CELL_NAME";
	public static final String TEST_STEP_CONTAINER_NAME = "TEST_STEP_CONTAINER_NAME";
	public static final String TEST_SUITE_NAME = "TEST_SUITE_NAME";
	public static final String TESTSTEP_REFERENCE_COMPONENT = "TESTSTEP_REFERENCE_COMPONENT";
	public static final String TESTSTEP_REFERENCE_STEP_OBJECT = "TESTSTEP_REFERENCE_STEP_OBJECT";
	public static final String TESTSTEP_REFERENCE_STEP_DEFINITION = "TESTSTEP_REFERENCE_STEP_DEFINITION";
	public static final String TESTSTEP_REFERENCE_STEP_PARAMETERS = "TESTSTEP_REFERENCE_STEP_PARAMETERS";
	// TODO leave this as 1 until name is split into 3 parts
	public static final String TEST_STEP_NAME = "TEST_STEP_NAME";

	@Check(CheckType.FAST)
	public void checkTestSuite(TestSuite theTestSuite) {
		// TODO validate that feature file name and feature name are the same.
		ITestSuite iTestSuite = new TestSuiteImpl(theTestSuite);
		String problems = TestSuiteIssueDetector.validateName(iTestSuite);
		if (!problems.isEmpty()) {
			warning(problems, SheepDogPackage.Literals.MODEL__NAME, TEST_SUITE_NAME);
		}
	}

	@Check(CheckType.NORMAL)
	public void checkTestStepContainer(TestStepContainer theTestStepContainer) {
		try {
			ITestStepContainer iTestStepContainer = new TestStepContainerImpl(theTestStepContainer);
			String problems = TestStepContainerIssueDetector.validateName(iTestStepContainer);
			if (!problems.isEmpty()) {
				warning(problems, SheepDogPackage.Literals.TEST_STEP_CONTAINER__NAME, TEST_STEP_CONTAINER_NAME);
			}
		} catch (Exception e) {
			logError(e, theTestStepContainer.getName());
		}
	}

	@Check(CheckType.EXPENSIVE)
	public void checkTestStep(TestStep step) {
		// TODO split into 2 checks, one for name syntax and one for reference
		// and rename to checkTestStepNameInvalid and checkTestStepRefNotFound
		try {
			if (step.getName() != null) {
				ITestStep iTestStep = new TestStepImpl(step);
				String problems = TestStepIssueDetector.validateName(iTestStep);
				if (!problems.isEmpty()) {
					error(problems, SheepDogPackage.Literals.TEST_STEP__NAME, TEST_STEP_NAME);
				} else {

					ITestProject testProject = new TestProjectImpl(
							new SourceFileRepository(step.eResource().getURI().toPlatformString(true)));
					iTestStep.getParent().getParent().setParent(testProject);
					problems = TestStepIssueDetector.validateReference(iTestStep);
					if (!problems.isEmpty()) {
						warning(problems, SheepDogPackage.Literals.TEST_STEP__NAME, problems);
					}
				}
			}
		} catch (Exception e) {
			logError(e, step.getName());
		}
	}
	
	@Check(CheckType.EXPENSIVE)
	public void checkRow(Row row) {
		TestStep step = (TestStep) row.eContainer().eContainer();
		try {
			if (step.getName() != null) {
				ITestStep iTestStep = new TestStepImpl(step);
				String problems = TestStepIssueDetector.validateName(iTestStep);
				if (!problems.isEmpty()) {
					error(problems, SheepDogPackage.Literals.TEST_STEP__NAME, TEST_STEP_NAME);
				} else {
					ITestProject testProject = new TestProjectImpl(
							new SourceFileRepository(step.eResource().getURI().toPlatformString(true)));
					iTestStep.getParent().getParent().setParent(testProject);
					problems = TestStepIssueDetector.validateReference(iTestStep);
					if (!problems.isEmpty()) {
						warning(problems, SheepDogPackage.Literals.TEST_STEP__NAME, problems);
					}
				}
			}
		} catch (Exception e) {
			logError(e, step.getName());
		}
	}

	@Check(CheckType.FAST)
	public void checkCell(Cell cell) {
		// TODO validate that each row should have the max number of columns
		// TODO make tests for this
		if (cell != null) {
			ICell iCell = new CellImpl(cell);
			IRow iRow = new RowImpl((Row) cell.eContainer());
			iCell.setParent(iRow);
			ITable iTable = new TableImpl((Table) cell.eContainer().eContainer());
			iRow.setParent(iTable);
			String problems = CellIssueDetector.validateName(iCell);
			if (!problems.isEmpty()) {
				warning(problems, SheepDogPackage.Literals.CELL__NAME, CELL_NAME);
			}
		}

	}

	private void logError(Exception e, String name) {
		logger.error("There was a problem for step: " + name);
		StringWriter sw = new StringWriter();
		e.printStackTrace(new PrintWriter(sw));
		logger.error(sw.toString());
	}
}
