/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.sheepdog.validation;

import java.io.PrintWriter;
import java.io.StringWriter;

import org.apache.log4j.Logger;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;
import org.farhan.dsl.sheepdog.sheepDog.TestStepContainer;
import org.farhan.dsl.sheepdog.impl.CellImpl;
import org.farhan.dsl.sheepdog.impl.RowImpl;
import org.farhan.dsl.sheepdog.impl.SourceFileRepository;
import org.farhan.dsl.sheepdog.impl.TestProjectImpl;
import org.farhan.dsl.sheepdog.impl.TestStepContainerImpl;
import org.farhan.dsl.sheepdog.impl.TestStepImpl;
import org.farhan.dsl.sheepdog.impl.TestSuiteImpl;
import org.farhan.dsl.sheepdog.impl.TextImpl;
import org.farhan.dsl.sheepdog.sheepDog.Cell;
import org.farhan.dsl.sheepdog.sheepDog.Row;
import org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage;
import org.farhan.dsl.sheepdog.sheepDog.TestSuite;
import org.farhan.dsl.sheepdog.sheepDog.TestStep;
import org.farhan.dsl.sheepdog.sheepDog.Table;
import org.farhan.dsl.sheepdog.sheepDog.Text;
import org.farhan.dsl.issues.*;
import org.farhan.dsl.lang.*;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SheepDogValidator extends AbstractSheepDogValidator {

	private static final Logger logger = Logger.getLogger(SheepDogValidator.class);
	public static final String CELL_NAME_ONLY = "CELL_NAME_ONLY";
	public static final String TEST_STEP_CONTAINER_NAME_ONLY = "TEST_STEP_CONTAINER_NAME_ONLY";
	public static final String TEST_STEP_CONTAINER_TEST_STEP_FILE_LIST_FILE = "TEST_STEP_CONTAINER_TEST_STEP_FILE_LIST_FILE";
	public static final String TEST_SUITE_NAME_ONLY = "TEST_SUITE_NAME_ONLY";
	public static final String TEST_STEP_NAME_OBJECT_WORKSPACE = "TEST_STEP_NAME_OBJECT_WORKSPACE";
	public static final String TEST_STEP_NAME_PREDICATE_WORKSPACE = "TEST_STEP_NAME_PREDICATE_WORKSPACE";
	public static final String ROW_CELL_LIST_WORKSPACE = "ROW_CELL_LIST_WORKSPACE";
	public static final String TEST_STEP_NAME_COMPONENT_ONLY = "TEST_STEP_NAME_COMPONENT_ONLY";
	public static final String TEST_STEP_NAME_OBJECT_ONLY = "TEST_STEP_NAME_OBJECT_ONLY";
	public static final String TEST_STEP_NAME_PREDICATE_ONLY = "TEST_STEP_NAME_PREDICATE_ONLY";
	public static final String TEXT_NAME_WORKSPACE = "TEXT_NAME_WORKSPACE";
	private static final EStructuralFeature TEST_STEP_NAME_STEP_PREDICATE_WORKSPACE = null;

	@Check(CheckType.FAST)
	public void checkTestSuiteNameOnly(TestSuite theTestSuite) {
		// TODO validate that feature file name and feature name are the same.
		TestSuiteImpl testSuiteImpl = new TestSuiteImpl(theTestSuite);
		String problems = TestSuiteIssueDetector.validateNameOnly(testSuiteImpl);
		if (!problems.isEmpty()) {
			warning(problems, SheepDogPackage.Literals.MODEL__NAME, TEST_SUITE_NAME_ONLY);
		}
	}

	@Check(CheckType.FAST)
	public void checkTestStepContainerNameOnly(TestStepContainer theTestStepContainer) {
		try {
			String problems = TestStepContainerIssueDetector
					.validateNameOnly(new TestStepContainerImpl(theTestStepContainer));
			if (!problems.isEmpty()) {
				warning(problems, SheepDogPackage.Literals.TEST_STEP_CONTAINER__NAME, TEST_STEP_CONTAINER_NAME_ONLY);
			}
		} catch (Exception e) {
			logError(e, theTestStepContainer.getName());
		}
	}

	@Check(CheckType.FAST)
	public void checkTestStepNameOnly(TestStep step) {
		try {
			if (step.getName() != null) {
				String problems = TestStepIssueDetector.validateNameComponentOnly(new TestStepImpl(step));
				if (!problems.isEmpty()) {
					error(problems, SheepDogPackage.Literals.TEST_STEP__NAME, TEST_STEP_NAME_COMPONENT_ONLY);
				} else {
					problems = TestStepIssueDetector.validateNameObjectOnly(new TestStepImpl(step));
					if (!problems.isEmpty()) {
						error(problems, SheepDogPackage.Literals.TEST_STEP__NAME, TEST_STEP_NAME_OBJECT_ONLY);
					} else {
						problems = TestStepIssueDetector.validateNamePredicateOnly(new TestStepImpl(step));
						if (!problems.isEmpty()) {
							error(problems, SheepDogPackage.Literals.TEST_STEP__NAME, TEST_STEP_NAME_PREDICATE_ONLY);
						}
					}
				}
			}
		} catch (Exception e) {
			logError(e, step.getName());
		}
	}

	@Check(CheckType.NORMAL)
	public void checkTestStepContainerTestStepFileListFile(TestStepContainer theTestStepContainer) {
		try {
			String problems = TestStepContainerIssueDetector
					.validateTestStepListFile(new TestStepContainerImpl(theTestStepContainer));
			if (!problems.isEmpty()) {
				warning(problems, SheepDogPackage.Literals.TEST_STEP_CONTAINER__TEST_STEP_LIST,
						TEST_STEP_CONTAINER_TEST_STEP_FILE_LIST_FILE);
			}
		} catch (Exception e) {
			logError(e, theTestStepContainer.getName());
		}
	}

	@Check(CheckType.EXPENSIVE)
	public void checkTestStepNameWorkspace(TestStep step) {
		try {
			if (step.getName() != null) {
				TestStepImpl testStepImpl = new TestStepImpl(step);
				testStepImpl.getParent().getParent().setParent(new TestProjectImpl(
						new SourceFileRepository(step.eResource().getURI().toPlatformString(true))));
				String problems = TestStepIssueDetector.validateNameObjectWorkspace(testStepImpl);
				if (!problems.isEmpty()) {
					warning(problems, SheepDogPackage.Literals.TEST_STEP__NAME, TEST_STEP_NAME_OBJECT_WORKSPACE);
				} else {
					problems = TestStepIssueDetector.validateNamePredicateWorkspace(testStepImpl);
					if (!problems.isEmpty()) {
						warning(problems, SheepDogPackage.Literals.TEST_STEP__NAME,
								TEST_STEP_NAME_STEP_PREDICATE_WORKSPACE);
					}
				}
			}
		} catch (Exception e) {
			logError(e, step.getName());
		}
	}

	@Check(CheckType.EXPENSIVE)
	public void checkRowCellListWorkspace(Row row) {
		try {
			if (row != null && row.eContainer() != null) {
				Table table = (Table) row.eContainer();
				if (table.eContainer() instanceof TestStep) {
					if (!table.getRowList().isEmpty() && table.getRowList().getFirst() == row) {
						RowImpl rowImpl = new RowImpl(row);
						((ITestStep) rowImpl.getParent().getParent()).getParent().getParent()
								.setParent(new TestProjectImpl(
										new SourceFileRepository(row.eResource().getURI().toPlatformString(true))));
						String problems = RowIssueDetector.validateCellListWorkspace(rowImpl);
						if (!problems.isEmpty()) {
							warning(problems, SheepDogPackage.Literals.ROW__CELL_LIST, ROW_CELL_LIST_WORKSPACE);
						}
					}
				}
			}
		} catch (Exception e) {
			logError(e, "Row validation");
		}
	}

	@Check(CheckType.FAST)
	public void checkCellNameOnly(Cell cell) {
		// TODO validate that each row should have the max number of columns
		// TODO make tests for this
		if (cell != null) {
			String problems = CellIssueDetector.validateNameOnly(new CellImpl(cell));
			if (!problems.isEmpty()) {
				warning(problems, SheepDogPackage.Literals.CELL__NAME, CELL_NAME_ONLY);
			}
		}
	}

	@Check(CheckType.EXPENSIVE)
	public void checkTextNameWorkspace(Text text) {
		if (text != null) {
			TextImpl textImpl = new TextImpl(text);
			textImpl.getParent().getParent().getParent().setParent(
					new TestProjectImpl(new SourceFileRepository(text.eResource().getURI().toPlatformString(true))));
			String problems = TextIssueDetector.validateNameWorkspace(textImpl);
			if (!problems.isEmpty()) {
				warning(problems, SheepDogPackage.Literals.TEXT__NAME, TEXT_NAME_WORKSPACE);
			}
		}
	}

	private void logError(Exception e, String name) {
		logger.error("There was a problem for step: " + name);
		StringWriter sw = new StringWriter();
		e.printStackTrace(new PrintWriter(sw));
		logger.error(sw.toString());
	}
}
