/*
 * generated by Xtext 2.42.0.M3
 */
package org.farhan.dsl.sheepdog.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SheepDogGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.Model");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStepObjectParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTestSuiteParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Model:
		//    StepObject | TestSuite;
		@Override public ParserRule getRule() { return rule; }
		
		//StepObject | TestSuite
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StepObject
		public RuleCall getStepObjectParserRuleCall_0() { return cStepObjectParserRuleCall_0; }
		
		//TestSuite
		public RuleCall getTestSuiteParserRuleCall_1() { return cTestSuiteParserRuleCall_1; }
	}
	public class StepObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.StepObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEqualsSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cStepObjectKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNamePhraseParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionDescriptionParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Assignment cStepDefinitionListAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStepDefinitionListStepDefinitionParserRuleCall_5_0 = (RuleCall)cStepDefinitionListAssignment_5.eContents().get(0);
		
		//StepObject:
		//    '=' 'Step-Object:' name=Phrase EOL
		//    description=Description?
		//    stepDefinitionList+=StepDefinition*;
		@Override public ParserRule getRule() { return rule; }
		
		//'=' 'Step-Object:' name=Phrase EOL
		//description=Description?
		//stepDefinitionList+=StepDefinition*
		public Group getGroup() { return cGroup; }
		
		//'='
		public Keyword getEqualsSignKeyword_0() { return cEqualsSignKeyword_0; }
		
		//'Step-Object:'
		public Keyword getStepObjectKeyword_1() { return cStepObjectKeyword_1; }
		
		//name=Phrase
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//Phrase
		public RuleCall getNamePhraseParserRuleCall_2_0() { return cNamePhraseParserRuleCall_2_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_3() { return cEOLTerminalRuleCall_3; }
		
		//description=Description?
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//Description
		public RuleCall getDescriptionDescriptionParserRuleCall_4_0() { return cDescriptionDescriptionParserRuleCall_4_0; }
		
		//stepDefinitionList+=StepDefinition*
		public Assignment getStepDefinitionListAssignment_5() { return cStepDefinitionListAssignment_5; }
		
		//StepDefinition
		public RuleCall getStepDefinitionListStepDefinitionParserRuleCall_5_0() { return cStepDefinitionListStepDefinitionParserRuleCall_5_0; }
	}
	public class StepDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.StepDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEqualsSignEqualsSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cStepDefinitionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNamePhraseParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionDescriptionParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Assignment cStepParameterListAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStepParameterListStepParametersParserRuleCall_5_0 = (RuleCall)cStepParameterListAssignment_5.eContents().get(0);
		
		//StepDefinition:
		//    '==' 'Step-Definition:' name=Phrase EOL
		//    description=Description?
		//    stepParameterList+=StepParameters*;
		@Override public ParserRule getRule() { return rule; }
		
		//'==' 'Step-Definition:' name=Phrase EOL
		//description=Description?
		//stepParameterList+=StepParameters*
		public Group getGroup() { return cGroup; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_0() { return cEqualsSignEqualsSignKeyword_0; }
		
		//'Step-Definition:'
		public Keyword getStepDefinitionKeyword_1() { return cStepDefinitionKeyword_1; }
		
		//name=Phrase
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//Phrase
		public RuleCall getNamePhraseParserRuleCall_2_0() { return cNamePhraseParserRuleCall_2_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_3() { return cEOLTerminalRuleCall_3; }
		
		//description=Description?
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//Description
		public RuleCall getDescriptionDescriptionParserRuleCall_4_0() { return cDescriptionDescriptionParserRuleCall_4_0; }
		
		//stepParameterList+=StepParameters*
		public Assignment getStepParameterListAssignment_5() { return cStepParameterListAssignment_5; }
		
		//StepParameters
		public RuleCall getStepParameterListStepParametersParserRuleCall_5_0() { return cStepParameterListStepParametersParserRuleCall_5_0; }
	}
	public class StepParametersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.StepParameters");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAsteriskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cStepParametersKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNamePhraseParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cNestedDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNestedDescriptionNestedDescriptionParserRuleCall_4_0 = (RuleCall)cNestedDescriptionAssignment_4.eContents().get(0);
		private final Assignment cTableAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTableTableParserRuleCall_5_0 = (RuleCall)cTableAssignment_5.eContents().get(0);
		
		//StepParameters:
		//    '*' 'Step-Parameters:' name=Phrase EOL
		//    nestedDescription=NestedDescription?
		//    table=Table;
		@Override public ParserRule getRule() { return rule; }
		
		//'*' 'Step-Parameters:' name=Phrase EOL
		//nestedDescription=NestedDescription?
		//table=Table
		public Group getGroup() { return cGroup; }
		
		//'*'
		public Keyword getAsteriskKeyword_0() { return cAsteriskKeyword_0; }
		
		//'Step-Parameters:'
		public Keyword getStepParametersKeyword_1() { return cStepParametersKeyword_1; }
		
		//name=Phrase
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//Phrase
		public RuleCall getNamePhraseParserRuleCall_2_0() { return cNamePhraseParserRuleCall_2_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_3() { return cEOLTerminalRuleCall_3; }
		
		//nestedDescription=NestedDescription?
		public Assignment getNestedDescriptionAssignment_4() { return cNestedDescriptionAssignment_4; }
		
		//NestedDescription
		public RuleCall getNestedDescriptionNestedDescriptionParserRuleCall_4_0() { return cNestedDescriptionNestedDescriptionParserRuleCall_4_0; }
		
		//table=Table
		public Assignment getTableAssignment_5() { return cTableAssignment_5; }
		
		//Table
		public RuleCall getTableTableParserRuleCall_5_0() { return cTableTableParserRuleCall_5_0; }
	}
	public class TestSuiteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.TestSuite");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEqualsSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTestSuiteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNamePhraseParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionDescriptionParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Assignment cTestStepContainerListAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTestStepContainerListTestStepContainerParserRuleCall_5_0 = (RuleCall)cTestStepContainerListAssignment_5.eContents().get(0);
		
		//TestSuite:
		//    '=' 'Test-Suite:' name=Phrase EOL
		//    description=Description?
		//    testStepContainerList+=TestStepContainer*;
		@Override public ParserRule getRule() { return rule; }
		
		//'=' 'Test-Suite:' name=Phrase EOL
		//description=Description?
		//testStepContainerList+=TestStepContainer*
		public Group getGroup() { return cGroup; }
		
		//'='
		public Keyword getEqualsSignKeyword_0() { return cEqualsSignKeyword_0; }
		
		//'Test-Suite:'
		public Keyword getTestSuiteKeyword_1() { return cTestSuiteKeyword_1; }
		
		//name=Phrase
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//Phrase
		public RuleCall getNamePhraseParserRuleCall_2_0() { return cNamePhraseParserRuleCall_2_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_3() { return cEOLTerminalRuleCall_3; }
		
		//description=Description?
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//Description
		public RuleCall getDescriptionDescriptionParserRuleCall_4_0() { return cDescriptionDescriptionParserRuleCall_4_0; }
		
		//testStepContainerList+=TestStepContainer*
		public Assignment getTestStepContainerListAssignment_5() { return cTestStepContainerListAssignment_5; }
		
		//TestStepContainer
		public RuleCall getTestStepContainerListTestStepContainerParserRuleCall_5_0() { return cTestStepContainerListTestStepContainerParserRuleCall_5_0; }
	}
	public class TestStepContainerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.TestStepContainer");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTestSetupParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTestCaseParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//TestStepContainer:
		//    TestSetup | TestCase;
		@Override public ParserRule getRule() { return rule; }
		
		//TestSetup | TestCase
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TestSetup
		public RuleCall getTestSetupParserRuleCall_0() { return cTestSetupParserRuleCall_0; }
		
		//TestCase
		public RuleCall getTestCaseParserRuleCall_1() { return cTestCaseParserRuleCall_1; }
	}
	public class TestSetupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.TestSetup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEqualsSignEqualsSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTestSetupKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNamePhraseParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionDescriptionParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Assignment cTestStepListAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTestStepListTestStepParserRuleCall_5_0 = (RuleCall)cTestStepListAssignment_5.eContents().get(0);
		
		//TestSetup:
		//    '==' 'Test-Setup:' name=Phrase EOL
		//    description=Description?
		//    testStepList+=TestStep*;
		@Override public ParserRule getRule() { return rule; }
		
		//'==' 'Test-Setup:' name=Phrase EOL
		//description=Description?
		//testStepList+=TestStep*
		public Group getGroup() { return cGroup; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_0() { return cEqualsSignEqualsSignKeyword_0; }
		
		//'Test-Setup:'
		public Keyword getTestSetupKeyword_1() { return cTestSetupKeyword_1; }
		
		//name=Phrase
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//Phrase
		public RuleCall getNamePhraseParserRuleCall_2_0() { return cNamePhraseParserRuleCall_2_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_3() { return cEOLTerminalRuleCall_3; }
		
		//description=Description?
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//Description
		public RuleCall getDescriptionDescriptionParserRuleCall_4_0() { return cDescriptionDescriptionParserRuleCall_4_0; }
		
		//testStepList+=TestStep*
		public Assignment getTestStepListAssignment_5() { return cTestStepListAssignment_5; }
		
		//TestStep
		public RuleCall getTestStepListTestStepParserRuleCall_5_0() { return cTestStepListTestStepParserRuleCall_5_0; }
	}
	public class TestCaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.TestCase");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEqualsSignEqualsSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTestCaseKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNamePhraseParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionDescriptionParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Assignment cTestStepListAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTestStepListTestStepParserRuleCall_5_0 = (RuleCall)cTestStepListAssignment_5.eContents().get(0);
		private final Assignment cTestDataListAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTestDataListTestDataParserRuleCall_6_0 = (RuleCall)cTestDataListAssignment_6.eContents().get(0);
		
		//TestCase:
		//    '==' 'Test-Case:' name=Phrase EOL
		//    description=Description?
		//    testStepList+=TestStep*
		//    testDataList+=TestData*;
		@Override public ParserRule getRule() { return rule; }
		
		//'==' 'Test-Case:' name=Phrase EOL
		//description=Description?
		//testStepList+=TestStep*
		//testDataList+=TestData*
		public Group getGroup() { return cGroup; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_0() { return cEqualsSignEqualsSignKeyword_0; }
		
		//'Test-Case:'
		public Keyword getTestCaseKeyword_1() { return cTestCaseKeyword_1; }
		
		//name=Phrase
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//Phrase
		public RuleCall getNamePhraseParserRuleCall_2_0() { return cNamePhraseParserRuleCall_2_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_3() { return cEOLTerminalRuleCall_3; }
		
		//description=Description?
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//Description
		public RuleCall getDescriptionDescriptionParserRuleCall_4_0() { return cDescriptionDescriptionParserRuleCall_4_0; }
		
		//testStepList+=TestStep*
		public Assignment getTestStepListAssignment_5() { return cTestStepListAssignment_5; }
		
		//TestStep
		public RuleCall getTestStepListTestStepParserRuleCall_5_0() { return cTestStepListTestStepParserRuleCall_5_0; }
		
		//testDataList+=TestData*
		public Assignment getTestDataListAssignment_6() { return cTestDataListAssignment_6; }
		
		//TestData
		public RuleCall getTestDataListTestDataParserRuleCall_6_0() { return cTestDataListTestDataParserRuleCall_6_0; }
	}
	public class TestDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.TestData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAsteriskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTestDataKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNamePhraseParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cNestedDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNestedDescriptionNestedDescriptionParserRuleCall_4_0 = (RuleCall)cNestedDescriptionAssignment_4.eContents().get(0);
		private final Assignment cTableAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTableTableParserRuleCall_5_0 = (RuleCall)cTableAssignment_5.eContents().get(0);
		
		//TestData:
		//    '*' 'Test-Data:' name=Phrase EOL
		//    nestedDescription=NestedDescription?
		//    table=Table;
		@Override public ParserRule getRule() { return rule; }
		
		//'*' 'Test-Data:' name=Phrase EOL
		//nestedDescription=NestedDescription?
		//table=Table
		public Group getGroup() { return cGroup; }
		
		//'*'
		public Keyword getAsteriskKeyword_0() { return cAsteriskKeyword_0; }
		
		//'Test-Data:'
		public Keyword getTestDataKeyword_1() { return cTestDataKeyword_1; }
		
		//name=Phrase
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//Phrase
		public RuleCall getNamePhraseParserRuleCall_2_0() { return cNamePhraseParserRuleCall_2_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_3() { return cEOLTerminalRuleCall_3; }
		
		//nestedDescription=NestedDescription?
		public Assignment getNestedDescriptionAssignment_4() { return cNestedDescriptionAssignment_4; }
		
		//NestedDescription
		public RuleCall getNestedDescriptionNestedDescriptionParserRuleCall_4_0() { return cNestedDescriptionNestedDescriptionParserRuleCall_4_0; }
		
		//table=Table
		public Assignment getTableAssignment_5() { return cTableAssignment_5; }
		
		//Table
		public RuleCall getTableTableParserRuleCall_5_0() { return cTableTableParserRuleCall_5_0; }
	}
	public class DescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.Description");
		private final Assignment cLineListAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cLineListLineParserRuleCall_0 = (RuleCall)cLineListAssignment.eContents().get(0);
		
		//Description:
		//    lineList+=Line+;
		@Override public ParserRule getRule() { return rule; }
		
		//lineList+=Line+
		public Assignment getLineListAssignment() { return cLineListAssignment; }
		
		//Line
		public RuleCall getLineListLineParserRuleCall_0() { return cLineListLineParserRuleCall_0; }
	}
	public class NestedDescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.NestedDescription");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cLineListAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLineListLineParserRuleCall_2_0 = (RuleCall)cLineListAssignment_2.eContents().get(0);
		
		//NestedDescription:
		//    '+' EOL
		//    lineList+=Line+;
		@Override public ParserRule getRule() { return rule; }
		
		//'+' EOL
		//lineList+=Line+
		public Group getGroup() { return cGroup; }
		
		//'+'
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_1() { return cEOLTerminalRuleCall_1; }
		
		//lineList+=Line+
		public Assignment getLineListAssignment_2() { return cLineListAssignment_2; }
		
		//Line
		public RuleCall getLineListLineParserRuleCall_2_0() { return cLineListLineParserRuleCall_2_0; }
	}
	public class TestStepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.TestStep");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGivenParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cWhenParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cThenParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cAndParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//TestStep:
		//    Given | When | Then | And;
		@Override public ParserRule getRule() { return rule; }
		
		//Given | When | Then | And
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Given
		public RuleCall getGivenParserRuleCall_0() { return cGivenParserRuleCall_0; }
		
		//When
		public RuleCall getWhenParserRuleCall_1() { return cWhenParserRuleCall_1; }
		
		//Then
		public RuleCall getThenParserRuleCall_2() { return cThenParserRuleCall_2; }
		
		//And
		public RuleCall getAndParserRuleCall_3() { return cAndParserRuleCall_3; }
	}
	public class GivenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.Given");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAsteriskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cGivenKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cStepObjectNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStepObjectNameStepObjectRefParserRuleCall_2_0 = (RuleCall)cStepObjectNameAssignment_2.eContents().get(0);
		private final Assignment cStepDefinitionNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStepDefinitionNameStepDefinitionRefParserRuleCall_3_0 = (RuleCall)cStepDefinitionNameAssignment_3.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Assignment cTableAssignment_5_0 = (Assignment)cAlternatives_5.eContents().get(0);
		private final RuleCall cTableTableParserRuleCall_5_0_0 = (RuleCall)cTableAssignment_5_0.eContents().get(0);
		private final Assignment cTextAssignment_5_1 = (Assignment)cAlternatives_5.eContents().get(1);
		private final RuleCall cTextTextParserRuleCall_5_1_0 = (RuleCall)cTextAssignment_5_1.eContents().get(0);
		
		//Given:
		//    '*' 'Given:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
		//    (table=Table | text=Text)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'*' 'Given:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
		//(table=Table | text=Text)?
		public Group getGroup() { return cGroup; }
		
		//'*'
		public Keyword getAsteriskKeyword_0() { return cAsteriskKeyword_0; }
		
		//'Given:'
		public Keyword getGivenKeyword_1() { return cGivenKeyword_1; }
		
		//stepObjectName=StepObjectRef
		public Assignment getStepObjectNameAssignment_2() { return cStepObjectNameAssignment_2; }
		
		//StepObjectRef
		public RuleCall getStepObjectNameStepObjectRefParserRuleCall_2_0() { return cStepObjectNameStepObjectRefParserRuleCall_2_0; }
		
		//stepDefinitionName=StepDefinitionRef
		public Assignment getStepDefinitionNameAssignment_3() { return cStepDefinitionNameAssignment_3; }
		
		//StepDefinitionRef
		public RuleCall getStepDefinitionNameStepDefinitionRefParserRuleCall_3_0() { return cStepDefinitionNameStepDefinitionRefParserRuleCall_3_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_4() { return cEOLTerminalRuleCall_4; }
		
		//(table=Table | text=Text)?
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//table=Table
		public Assignment getTableAssignment_5_0() { return cTableAssignment_5_0; }
		
		//Table
		public RuleCall getTableTableParserRuleCall_5_0_0() { return cTableTableParserRuleCall_5_0_0; }
		
		//text=Text
		public Assignment getTextAssignment_5_1() { return cTextAssignment_5_1; }
		
		//Text
		public RuleCall getTextTextParserRuleCall_5_1_0() { return cTextTextParserRuleCall_5_1_0; }
	}
	public class WhenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.When");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAsteriskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cWhenKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cStepObjectNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStepObjectNameStepObjectRefParserRuleCall_2_0 = (RuleCall)cStepObjectNameAssignment_2.eContents().get(0);
		private final Assignment cStepDefinitionNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStepDefinitionNameStepDefinitionRefParserRuleCall_3_0 = (RuleCall)cStepDefinitionNameAssignment_3.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Assignment cTableAssignment_5_0 = (Assignment)cAlternatives_5.eContents().get(0);
		private final RuleCall cTableTableParserRuleCall_5_0_0 = (RuleCall)cTableAssignment_5_0.eContents().get(0);
		private final Assignment cTextAssignment_5_1 = (Assignment)cAlternatives_5.eContents().get(1);
		private final RuleCall cTextTextParserRuleCall_5_1_0 = (RuleCall)cTextAssignment_5_1.eContents().get(0);
		
		//When:
		//    '*' 'When:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
		//    (table=Table | text=Text)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'*' 'When:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
		//(table=Table | text=Text)?
		public Group getGroup() { return cGroup; }
		
		//'*'
		public Keyword getAsteriskKeyword_0() { return cAsteriskKeyword_0; }
		
		//'When:'
		public Keyword getWhenKeyword_1() { return cWhenKeyword_1; }
		
		//stepObjectName=StepObjectRef
		public Assignment getStepObjectNameAssignment_2() { return cStepObjectNameAssignment_2; }
		
		//StepObjectRef
		public RuleCall getStepObjectNameStepObjectRefParserRuleCall_2_0() { return cStepObjectNameStepObjectRefParserRuleCall_2_0; }
		
		//stepDefinitionName=StepDefinitionRef
		public Assignment getStepDefinitionNameAssignment_3() { return cStepDefinitionNameAssignment_3; }
		
		//StepDefinitionRef
		public RuleCall getStepDefinitionNameStepDefinitionRefParserRuleCall_3_0() { return cStepDefinitionNameStepDefinitionRefParserRuleCall_3_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_4() { return cEOLTerminalRuleCall_4; }
		
		//(table=Table | text=Text)?
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//table=Table
		public Assignment getTableAssignment_5_0() { return cTableAssignment_5_0; }
		
		//Table
		public RuleCall getTableTableParserRuleCall_5_0_0() { return cTableTableParserRuleCall_5_0_0; }
		
		//text=Text
		public Assignment getTextAssignment_5_1() { return cTextAssignment_5_1; }
		
		//Text
		public RuleCall getTextTextParserRuleCall_5_1_0() { return cTextTextParserRuleCall_5_1_0; }
	}
	public class ThenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.Then");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAsteriskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cThenKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cStepObjectNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStepObjectNameStepObjectRefParserRuleCall_2_0 = (RuleCall)cStepObjectNameAssignment_2.eContents().get(0);
		private final Assignment cStepDefinitionNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStepDefinitionNameStepDefinitionRefParserRuleCall_3_0 = (RuleCall)cStepDefinitionNameAssignment_3.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Assignment cTableAssignment_5_0 = (Assignment)cAlternatives_5.eContents().get(0);
		private final RuleCall cTableTableParserRuleCall_5_0_0 = (RuleCall)cTableAssignment_5_0.eContents().get(0);
		private final Assignment cTextAssignment_5_1 = (Assignment)cAlternatives_5.eContents().get(1);
		private final RuleCall cTextTextParserRuleCall_5_1_0 = (RuleCall)cTextAssignment_5_1.eContents().get(0);
		
		//Then:
		//    '*' 'Then:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
		//    (table=Table | text=Text)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'*' 'Then:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
		//(table=Table | text=Text)?
		public Group getGroup() { return cGroup; }
		
		//'*'
		public Keyword getAsteriskKeyword_0() { return cAsteriskKeyword_0; }
		
		//'Then:'
		public Keyword getThenKeyword_1() { return cThenKeyword_1; }
		
		//stepObjectName=StepObjectRef
		public Assignment getStepObjectNameAssignment_2() { return cStepObjectNameAssignment_2; }
		
		//StepObjectRef
		public RuleCall getStepObjectNameStepObjectRefParserRuleCall_2_0() { return cStepObjectNameStepObjectRefParserRuleCall_2_0; }
		
		//stepDefinitionName=StepDefinitionRef
		public Assignment getStepDefinitionNameAssignment_3() { return cStepDefinitionNameAssignment_3; }
		
		//StepDefinitionRef
		public RuleCall getStepDefinitionNameStepDefinitionRefParserRuleCall_3_0() { return cStepDefinitionNameStepDefinitionRefParserRuleCall_3_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_4() { return cEOLTerminalRuleCall_4; }
		
		//(table=Table | text=Text)?
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//table=Table
		public Assignment getTableAssignment_5_0() { return cTableAssignment_5_0; }
		
		//Table
		public RuleCall getTableTableParserRuleCall_5_0_0() { return cTableTableParserRuleCall_5_0_0; }
		
		//text=Text
		public Assignment getTextAssignment_5_1() { return cTextAssignment_5_1; }
		
		//Text
		public RuleCall getTextTextParserRuleCall_5_1_0() { return cTextTextParserRuleCall_5_1_0; }
	}
	public class AndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.And");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAsteriskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAndKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cStepObjectNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStepObjectNameStepObjectRefParserRuleCall_2_0 = (RuleCall)cStepObjectNameAssignment_2.eContents().get(0);
		private final Assignment cStepDefinitionNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStepDefinitionNameStepDefinitionRefParserRuleCall_3_0 = (RuleCall)cStepDefinitionNameAssignment_3.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Assignment cTableAssignment_5_0 = (Assignment)cAlternatives_5.eContents().get(0);
		private final RuleCall cTableTableParserRuleCall_5_0_0 = (RuleCall)cTableAssignment_5_0.eContents().get(0);
		private final Assignment cTextAssignment_5_1 = (Assignment)cAlternatives_5.eContents().get(1);
		private final RuleCall cTextTextParserRuleCall_5_1_0 = (RuleCall)cTextAssignment_5_1.eContents().get(0);
		
		//And:
		//    '*' 'And:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
		//    (table=Table | text=Text)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'*' 'And:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
		//(table=Table | text=Text)?
		public Group getGroup() { return cGroup; }
		
		//'*'
		public Keyword getAsteriskKeyword_0() { return cAsteriskKeyword_0; }
		
		//'And:'
		public Keyword getAndKeyword_1() { return cAndKeyword_1; }
		
		//stepObjectName=StepObjectRef
		public Assignment getStepObjectNameAssignment_2() { return cStepObjectNameAssignment_2; }
		
		//StepObjectRef
		public RuleCall getStepObjectNameStepObjectRefParserRuleCall_2_0() { return cStepObjectNameStepObjectRefParserRuleCall_2_0; }
		
		//stepDefinitionName=StepDefinitionRef
		public Assignment getStepDefinitionNameAssignment_3() { return cStepDefinitionNameAssignment_3; }
		
		//StepDefinitionRef
		public RuleCall getStepDefinitionNameStepDefinitionRefParserRuleCall_3_0() { return cStepDefinitionNameStepDefinitionRefParserRuleCall_3_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_4() { return cEOLTerminalRuleCall_4; }
		
		//(table=Table | text=Text)?
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//table=Table
		public Assignment getTableAssignment_5_0() { return cTableAssignment_5_0; }
		
		//Table
		public RuleCall getTableTableParserRuleCall_5_0_0() { return cTableTableParserRuleCall_5_0_0; }
		
		//text=Text
		public Assignment getTextAssignment_5_1() { return cTextAssignment_5_1; }
		
		//Text
		public RuleCall getTextTextParserRuleCall_5_1_0() { return cTextTextParserRuleCall_5_1_0; }
	}
	public class TextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.Text");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameRAWTEXTTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//Text:
		//    '+' EOL
		//    name=RAWTEXT EOL;
		@Override public ParserRule getRule() { return rule; }
		
		//'+' EOL
		//name=RAWTEXT EOL
		public Group getGroup() { return cGroup; }
		
		//'+'
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_1() { return cEOLTerminalRuleCall_1; }
		
		//name=RAWTEXT
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//RAWTEXT
		public RuleCall getNameRAWTEXTTerminalRuleCall_2_0() { return cNameRAWTEXTTerminalRuleCall_2_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_3() { return cEOLTerminalRuleCall_3; }
	}
	public class TableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.Table");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cVerticalLineEqualsSignEqualsSignEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cEOLTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cRowListAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRowListRowParserRuleCall_4_0 = (RuleCall)cRowListAssignment_4.eContents().get(0);
		private final Keyword cVerticalLineEqualsSignEqualsSignEqualsSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final RuleCall cEOLTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		
		//Table:
		//    '+' EOL
		//    '|===' EOL
		//    rowList+=Row+
		//    '|===' EOL;
		@Override public ParserRule getRule() { return rule; }
		
		//'+' EOL
		//'|===' EOL
		//rowList+=Row+
		//'|===' EOL
		public Group getGroup() { return cGroup; }
		
		//'+'
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_1() { return cEOLTerminalRuleCall_1; }
		
		//'|==='
		public Keyword getVerticalLineEqualsSignEqualsSignEqualsSignKeyword_2() { return cVerticalLineEqualsSignEqualsSignEqualsSignKeyword_2; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_3() { return cEOLTerminalRuleCall_3; }
		
		//rowList+=Row+
		public Assignment getRowListAssignment_4() { return cRowListAssignment_4; }
		
		//Row
		public RuleCall getRowListRowParserRuleCall_4_0() { return cRowListRowParserRuleCall_4_0; }
		
		//'|==='
		public Keyword getVerticalLineEqualsSignEqualsSignEqualsSignKeyword_5() { return cVerticalLineEqualsSignEqualsSignEqualsSignKeyword_5; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_6() { return cEOLTerminalRuleCall_6; }
	}
	public class RowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.Row");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCellListAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cCellListCellParserRuleCall_0_0 = (RuleCall)cCellListAssignment_0.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Row:
		//    cellList+=Cell+ EOL;
		@Override public ParserRule getRule() { return rule; }
		
		//cellList+=Cell+ EOL
		public Group getGroup() { return cGroup; }
		
		//cellList+=Cell+
		public Assignment getCellListAssignment_0() { return cCellListAssignment_0; }
		
		//Cell
		public RuleCall getCellListCellParserRuleCall_0_0() { return cCellListCellParserRuleCall_0_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_1() { return cEOLTerminalRuleCall_1; }
	}
	public class CellElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.Cell");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVerticalLineKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNamePhraseParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Cell:
		//    '|' name=Phrase;
		@Override public ParserRule getRule() { return rule; }
		
		//'|' name=Phrase
		public Group getGroup() { return cGroup; }
		
		//'|'
		public Keyword getVerticalLineKeyword_0() { return cVerticalLineKeyword_0; }
		
		//name=Phrase
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//Phrase
		public RuleCall getNamePhraseParserRuleCall_1_0() { return cNamePhraseParserRuleCall_1_0; }
	}
	public class LineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.Line");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNamePhraseParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final RuleCall cEOLTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Line:
		//    name=Phrase EOL;
		@Override public ParserRule getRule() { return rule; }
		
		//name=Phrase EOL
		public Group getGroup() { return cGroup; }
		
		//name=Phrase
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//Phrase
		public RuleCall getNamePhraseParserRuleCall_0_0() { return cNamePhraseParserRuleCall_0_0; }
		
		//EOL
		public RuleCall getEOLTerminalRuleCall_1() { return cEOLTerminalRuleCall_1; }
	}
	public class PhraseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.Phrase");
		private final RuleCall cWORDTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Phrase:
		//    WORD+;
		@Override public ParserRule getRule() { return rule; }
		
		//WORD+
		public RuleCall getWORDTerminalRuleCall() { return cWORDTerminalRuleCall; }
	}
	public class StepObjectRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.StepObjectRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cWORDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cFileKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cPageKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Keyword cResponseKeyword_1_2 = (Keyword)cAlternatives_1.eContents().get(2);
		private final Keyword cDialogKeyword_1_3 = (Keyword)cAlternatives_1.eContents().get(3);
		private final Keyword cDirectoryKeyword_1_4 = (Keyword)cAlternatives_1.eContents().get(4);
		private final Keyword cRequestKeyword_1_5 = (Keyword)cAlternatives_1.eContents().get(5);
		private final Keyword cGoalKeyword_1_6 = (Keyword)cAlternatives_1.eContents().get(6);
		private final Keyword cJobKeyword_1_7 = (Keyword)cAlternatives_1.eContents().get(7);
		private final Keyword cActionKeyword_1_8 = (Keyword)cAlternatives_1.eContents().get(8);
		private final Keyword cPopupKeyword_1_9 = (Keyword)cAlternatives_1.eContents().get(9);
		private final Keyword cAnnotationKeyword_1_10 = (Keyword)cAlternatives_1.eContents().get(10);
		private final Keyword cHoverKeyword_1_11 = (Keyword)cAlternatives_1.eContents().get(11);
		private final Keyword cTooltipKeyword_1_12 = (Keyword)cAlternatives_1.eContents().get(12);
		
		//// TODO the regular expression here is a partial duplication of what's in sheep-dog-test
		//// It should only be defined here but that is more work than I want to do right now
		//// When testing sheep-dog-test, it doesn't need a regex.
		//// It's enough that the Impl classes return what parts it needs.
		//// If all the parts accessible from the utility are defined here,
		//// then the TestStepImpl class + its utility can extract that information
		//// Also any tests in sheep-dog-test must be implemented in the xtext project
		//// to make sure the Impl classes have implemented this correctly
		//// For now I'm putting the whole regex to make it possible to distinguish between STEP_OBJECT and STEP_DEFINITION
		//// without breaking it up into its parts
		//StepObjectRef:
		//    WORD+ ('file' | 'page' | 'response' | 'dialog' | 'directory' | 'request' | 'goal' | 'job' | 'action' | 'popup' | 'annotation' | 'hover' | 'tooltip');
		@Override public ParserRule getRule() { return rule; }
		
		//WORD+ ('file' | 'page' | 'response' | 'dialog' | 'directory' | 'request' | 'goal' | 'job' | 'action' | 'popup' | 'annotation' | 'hover' | 'tooltip')
		public Group getGroup() { return cGroup; }
		
		//WORD+
		public RuleCall getWORDTerminalRuleCall_0() { return cWORDTerminalRuleCall_0; }
		
		//('file' | 'page' | 'response' | 'dialog' | 'directory' | 'request' | 'goal' | 'job' | 'action' | 'popup' | 'annotation' | 'hover' | 'tooltip')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'file'
		public Keyword getFileKeyword_1_0() { return cFileKeyword_1_0; }
		
		//'page'
		public Keyword getPageKeyword_1_1() { return cPageKeyword_1_1; }
		
		//'response'
		public Keyword getResponseKeyword_1_2() { return cResponseKeyword_1_2; }
		
		//'dialog'
		public Keyword getDialogKeyword_1_3() { return cDialogKeyword_1_3; }
		
		//'directory'
		public Keyword getDirectoryKeyword_1_4() { return cDirectoryKeyword_1_4; }
		
		//'request'
		public Keyword getRequestKeyword_1_5() { return cRequestKeyword_1_5; }
		
		//'goal'
		public Keyword getGoalKeyword_1_6() { return cGoalKeyword_1_6; }
		
		//'job'
		public Keyword getJobKeyword_1_7() { return cJobKeyword_1_7; }
		
		//'action'
		public Keyword getActionKeyword_1_8() { return cActionKeyword_1_8; }
		
		//'popup'
		public Keyword getPopupKeyword_1_9() { return cPopupKeyword_1_9; }
		
		//'annotation'
		public Keyword getAnnotationKeyword_1_10() { return cAnnotationKeyword_1_10; }
		
		//'hover'
		public Keyword getHoverKeyword_1_11() { return cHoverKeyword_1_11; }
		
		//'tooltip'
		public Keyword getTooltipKeyword_1_12() { return cTooltipKeyword_1_12; }
	}
	public class StepDefinitionRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.StepDefinitionRef");
		private final RuleCall cWORDTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//StepDefinitionRef:
		//    WORD+;
		@Override public ParserRule getRule() { return rule; }
		
		//WORD+
		public RuleCall getWORDTerminalRuleCall() { return cWORDTerminalRuleCall; }
	}
	
	
	private final ModelElements pModel;
	private final StepObjectElements pStepObject;
	private final StepDefinitionElements pStepDefinition;
	private final StepParametersElements pStepParameters;
	private final TestSuiteElements pTestSuite;
	private final TestStepContainerElements pTestStepContainer;
	private final TestSetupElements pTestSetup;
	private final TestCaseElements pTestCase;
	private final TestDataElements pTestData;
	private final DescriptionElements pDescription;
	private final NestedDescriptionElements pNestedDescription;
	private final TestStepElements pTestStep;
	private final GivenElements pGiven;
	private final WhenElements pWhen;
	private final ThenElements pThen;
	private final AndElements pAnd;
	private final TextElements pText;
	private final TableElements pTable;
	private final RowElements pRow;
	private final CellElements pCell;
	private final LineElements pLine;
	private final PhraseElements pPhrase;
	private final StepObjectRefElements pStepObjectRef;
	private final StepDefinitionRefElements pStepDefinitionRef;
	private final TerminalRule tWS;
	private final TerminalRule tSL_COMMENT;
	private final TerminalRule tEOL;
	private final TerminalRule tRAWTEXT;
	private final TerminalRule tWORD;
	
	private final Grammar grammar;

	@Inject
	public SheepDogGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.pModel = new ModelElements();
		this.pStepObject = new StepObjectElements();
		this.pStepDefinition = new StepDefinitionElements();
		this.pStepParameters = new StepParametersElements();
		this.pTestSuite = new TestSuiteElements();
		this.pTestStepContainer = new TestStepContainerElements();
		this.pTestSetup = new TestSetupElements();
		this.pTestCase = new TestCaseElements();
		this.pTestData = new TestDataElements();
		this.pDescription = new DescriptionElements();
		this.pNestedDescription = new NestedDescriptionElements();
		this.pTestStep = new TestStepElements();
		this.pGiven = new GivenElements();
		this.pWhen = new WhenElements();
		this.pThen = new ThenElements();
		this.pAnd = new AndElements();
		this.pText = new TextElements();
		this.pTable = new TableElements();
		this.pRow = new RowElements();
		this.pCell = new CellElements();
		this.pLine = new LineElements();
		this.pPhrase = new PhraseElements();
		this.pStepObjectRef = new StepObjectRefElements();
		this.pStepDefinitionRef = new StepDefinitionRefElements();
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.WS");
		this.tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.SL_COMMENT");
		this.tEOL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.EOL");
		this.tRAWTEXT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.RAWTEXT");
		this.tWORD = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.farhan.dsl.sheepdog.SheepDog.WORD");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.farhan.dsl.sheepdog.SheepDog".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//Model:
	//    StepObject | TestSuite;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//StepObject:
	//    '=' 'Step-Object:' name=Phrase EOL
	//    description=Description?
	//    stepDefinitionList+=StepDefinition*;
	public StepObjectElements getStepObjectAccess() {
		return pStepObject;
	}
	
	public ParserRule getStepObjectRule() {
		return getStepObjectAccess().getRule();
	}
	
	//StepDefinition:
	//    '==' 'Step-Definition:' name=Phrase EOL
	//    description=Description?
	//    stepParameterList+=StepParameters*;
	public StepDefinitionElements getStepDefinitionAccess() {
		return pStepDefinition;
	}
	
	public ParserRule getStepDefinitionRule() {
		return getStepDefinitionAccess().getRule();
	}
	
	//StepParameters:
	//    '*' 'Step-Parameters:' name=Phrase EOL
	//    nestedDescription=NestedDescription?
	//    table=Table;
	public StepParametersElements getStepParametersAccess() {
		return pStepParameters;
	}
	
	public ParserRule getStepParametersRule() {
		return getStepParametersAccess().getRule();
	}
	
	//TestSuite:
	//    '=' 'Test-Suite:' name=Phrase EOL
	//    description=Description?
	//    testStepContainerList+=TestStepContainer*;
	public TestSuiteElements getTestSuiteAccess() {
		return pTestSuite;
	}
	
	public ParserRule getTestSuiteRule() {
		return getTestSuiteAccess().getRule();
	}
	
	//TestStepContainer:
	//    TestSetup | TestCase;
	public TestStepContainerElements getTestStepContainerAccess() {
		return pTestStepContainer;
	}
	
	public ParserRule getTestStepContainerRule() {
		return getTestStepContainerAccess().getRule();
	}
	
	//TestSetup:
	//    '==' 'Test-Setup:' name=Phrase EOL
	//    description=Description?
	//    testStepList+=TestStep*;
	public TestSetupElements getTestSetupAccess() {
		return pTestSetup;
	}
	
	public ParserRule getTestSetupRule() {
		return getTestSetupAccess().getRule();
	}
	
	//TestCase:
	//    '==' 'Test-Case:' name=Phrase EOL
	//    description=Description?
	//    testStepList+=TestStep*
	//    testDataList+=TestData*;
	public TestCaseElements getTestCaseAccess() {
		return pTestCase;
	}
	
	public ParserRule getTestCaseRule() {
		return getTestCaseAccess().getRule();
	}
	
	//TestData:
	//    '*' 'Test-Data:' name=Phrase EOL
	//    nestedDescription=NestedDescription?
	//    table=Table;
	public TestDataElements getTestDataAccess() {
		return pTestData;
	}
	
	public ParserRule getTestDataRule() {
		return getTestDataAccess().getRule();
	}
	
	//Description:
	//    lineList+=Line+;
	public DescriptionElements getDescriptionAccess() {
		return pDescription;
	}
	
	public ParserRule getDescriptionRule() {
		return getDescriptionAccess().getRule();
	}
	
	//NestedDescription:
	//    '+' EOL
	//    lineList+=Line+;
	public NestedDescriptionElements getNestedDescriptionAccess() {
		return pNestedDescription;
	}
	
	public ParserRule getNestedDescriptionRule() {
		return getNestedDescriptionAccess().getRule();
	}
	
	//TestStep:
	//    Given | When | Then | And;
	public TestStepElements getTestStepAccess() {
		return pTestStep;
	}
	
	public ParserRule getTestStepRule() {
		return getTestStepAccess().getRule();
	}
	
	//Given:
	//    '*' 'Given:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
	//    (table=Table | text=Text)?;
	public GivenElements getGivenAccess() {
		return pGiven;
	}
	
	public ParserRule getGivenRule() {
		return getGivenAccess().getRule();
	}
	
	//When:
	//    '*' 'When:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
	//    (table=Table | text=Text)?;
	public WhenElements getWhenAccess() {
		return pWhen;
	}
	
	public ParserRule getWhenRule() {
		return getWhenAccess().getRule();
	}
	
	//Then:
	//    '*' 'Then:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
	//    (table=Table | text=Text)?;
	public ThenElements getThenAccess() {
		return pThen;
	}
	
	public ParserRule getThenRule() {
		return getThenAccess().getRule();
	}
	
	//And:
	//    '*' 'And:' stepObjectName=StepObjectRef stepDefinitionName=StepDefinitionRef EOL
	//    (table=Table | text=Text)?;
	public AndElements getAndAccess() {
		return pAnd;
	}
	
	public ParserRule getAndRule() {
		return getAndAccess().getRule();
	}
	
	//Text:
	//    '+' EOL
	//    name=RAWTEXT EOL;
	public TextElements getTextAccess() {
		return pText;
	}
	
	public ParserRule getTextRule() {
		return getTextAccess().getRule();
	}
	
	//Table:
	//    '+' EOL
	//    '|===' EOL
	//    rowList+=Row+
	//    '|===' EOL;
	public TableElements getTableAccess() {
		return pTable;
	}
	
	public ParserRule getTableRule() {
		return getTableAccess().getRule();
	}
	
	//Row:
	//    cellList+=Cell+ EOL;
	public RowElements getRowAccess() {
		return pRow;
	}
	
	public ParserRule getRowRule() {
		return getRowAccess().getRule();
	}
	
	//Cell:
	//    '|' name=Phrase;
	public CellElements getCellAccess() {
		return pCell;
	}
	
	public ParserRule getCellRule() {
		return getCellAccess().getRule();
	}
	
	//Line:
	//    name=Phrase EOL;
	public LineElements getLineAccess() {
		return pLine;
	}
	
	public ParserRule getLineRule() {
		return getLineAccess().getRule();
	}
	
	//Phrase:
	//    WORD+;
	public PhraseElements getPhraseAccess() {
		return pPhrase;
	}
	
	public ParserRule getPhraseRule() {
		return getPhraseAccess().getRule();
	}
	
	//// TODO the regular expression here is a partial duplication of what's in sheep-dog-test
	//// It should only be defined here but that is more work than I want to do right now
	//// When testing sheep-dog-test, it doesn't need a regex.
	//// It's enough that the Impl classes return what parts it needs.
	//// If all the parts accessible from the utility are defined here,
	//// then the TestStepImpl class + its utility can extract that information
	//// Also any tests in sheep-dog-test must be implemented in the xtext project
	//// to make sure the Impl classes have implemented this correctly
	//// For now I'm putting the whole regex to make it possible to distinguish between STEP_OBJECT and STEP_DEFINITION
	//// without breaking it up into its parts
	//StepObjectRef:
	//    WORD+ ('file' | 'page' | 'response' | 'dialog' | 'directory' | 'request' | 'goal' | 'job' | 'action' | 'popup' | 'annotation' | 'hover' | 'tooltip');
	public StepObjectRefElements getStepObjectRefAccess() {
		return pStepObjectRef;
	}
	
	public ParserRule getStepObjectRefRule() {
		return getStepObjectRefAccess().getRule();
	}
	
	//StepDefinitionRef:
	//    WORD+;
	public StepDefinitionRefElements getStepDefinitionRefAccess() {
		return pStepDefinitionRef;
	}
	
	public ParserRule getStepDefinitionRefRule() {
		return getStepDefinitionRefAccess().getRule();
	}
	
	//terminal WS:
	//    (' ' | '\t' | '\r')+;
	public TerminalRule getWSRule() {
		return tWS;
	}
	
	//terminal SL_COMMENT:
	//    '#' !('\n')* EOL;
	public TerminalRule getSL_COMMENTRule() {
		return tSL_COMMENT;
	}
	
	//terminal EOL:
	//    ('\n')+;
	public TerminalRule getEOLRule() {
		return tEOL;
	}
	
	//terminal RAWTEXT:
	//    '----' '\n' (.)+ '\n' '----';
	public TerminalRule getRAWTEXTRule() {
		return tRAWTEXT;
	}
	
	//terminal WORD:
	//    !(' ' | '\t' | '\r' | '\n')+;
	public TerminalRule getWORDRule() {
		return tWORD;
	}
}
