/**
 * generated by Xtext 2.41.0
 */
package org.farhan.dsl.cucumber.cucumber;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Background</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.farhan.dsl.cucumber.cucumber.CucumberPackage#getBackground()
 * @model
 * @generated
 */
public interface Background extends AbstractScenario
{
} // Background
