/**
 * generated by Xtext 2.42.0.M2
 */
package org.farhan.dsl.sheepdog.sheepDog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getAnd()
 * @model
 * @generated
 */
public interface And extends TestStep
{
} // And
