/**
 * generated by Xtext 2.42.0.M3
 */
package org.farhan.dsl.sheepdog.sheepDog;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nested Statement List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.NestedStatementList#getStatementList <em>Statement List</em>}</li>
 * </ul>
 *
 * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getNestedStatementList()
 * @model
 * @generated
 */
public interface NestedStatementList extends EObject
{
  /**
   * Returns the value of the '<em><b>Statement List</b></em>' containment reference list.
   * The list contents are of type {@link org.farhan.dsl.sheepdog.sheepDog.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement List</em>' containment reference list.
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getNestedStatementList_StatementList()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatementList();

} // NestedStatementList
