/**
 * generated by Xtext 2.42.0
 */
package org.farhan.dsl.sheepdog.sheepDog;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nested Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.NestedDescription#getLineList <em>Line List</em>}</li>
 * </ul>
 *
 * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getNestedDescription()
 * @model
 * @generated
 */
public interface NestedDescription extends EObject
{
  /**
   * Returns the value of the '<em><b>Line List</b></em>' containment reference list.
   * The list contents are of type {@link org.farhan.dsl.sheepdog.sheepDog.Line}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line List</em>' containment reference list.
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getNestedDescription_LineList()
   * @model containment="true"
   * @generated
   */
  EList<Line> getLineList();

} // NestedDescription
