/**
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.sheepdog.sheepDog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.StepReference#getObject <em>Object</em>}</li>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.StepReference#getPredicate <em>Predicate</em>}</li>
 * </ul>
 *
 * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getStepReference()
 * @model
 * @generated
 */
public interface StepReference extends EObject
{
  /**
   * Returns the value of the '<em><b>Object</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' attribute.
   * @see #setObject(String)
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getStepReference_Object()
   * @model
   * @generated
   */
  String getObject();

  /**
   * Sets the value of the '{@link org.farhan.dsl.sheepdog.sheepDog.StepReference#getObject <em>Object</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' attribute.
   * @see #getObject()
   * @generated
   */
  void setObject(String value);

  /**
   * Returns the value of the '<em><b>Predicate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate</em>' attribute.
   * @see #setPredicate(String)
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getStepReference_Predicate()
   * @model
   * @generated
   */
  String getPredicate();

  /**
   * Sets the value of the '{@link org.farhan.dsl.sheepdog.sheepDog.StepReference#getPredicate <em>Predicate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate</em>' attribute.
   * @see #getPredicate()
   * @generated
   */
  void setPredicate(String value);

} // StepReference
