/**
 * generated by Xtext 2.42.0.M2
 */
package org.farhan.dsl.sheepdog.sheepDog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getStepObjectName <em>Step Object Name</em>}</li>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getStepDefinitionName <em>Step Definition Name</em>}</li>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getTable <em>Table</em>}</li>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getTestStep()
 * @model
 * @generated
 */
public interface TestStep extends EObject
{
  /**
   * Returns the value of the '<em><b>Step Object Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step Object Name</em>' attribute.
   * @see #setStepObjectName(String)
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getTestStep_StepObjectName()
   * @model
   * @generated
   */
  String getStepObjectName();

  /**
   * Sets the value of the '{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getStepObjectName <em>Step Object Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Step Object Name</em>' attribute.
   * @see #getStepObjectName()
   * @generated
   */
  void setStepObjectName(String value);

  /**
   * Returns the value of the '<em><b>Step Definition Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step Definition Name</em>' attribute.
   * @see #setStepDefinitionName(String)
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getTestStep_StepDefinitionName()
   * @model
   * @generated
   */
  String getStepDefinitionName();

  /**
   * Sets the value of the '{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getStepDefinitionName <em>Step Definition Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Step Definition Name</em>' attribute.
   * @see #getStepDefinitionName()
   * @generated
   */
  void setStepDefinitionName(String value);

  /**
   * Returns the value of the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' containment reference.
   * @see #setTable(Table)
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getTestStep_Table()
   * @model containment="true"
   * @generated
   */
  Table getTable();

  /**
   * Sets the value of the '{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getTable <em>Table</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' containment reference.
   * @see #getTable()
   * @generated
   */
  void setTable(Table value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference.
   * @see #setText(Text)
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getTestStep_Text()
   * @model containment="true"
   * @generated
   */
  Text getText();

  /**
   * Sets the value of the '{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getText <em>Text</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' containment reference.
   * @see #getText()
   * @generated
   */
  void setText(Text value);

} // TestStep
