/**
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.sheepdog.sheepDog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getObject <em>Object</em>}</li>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getPredicate <em>Predicate</em>}</li>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getTable <em>Table</em>}</li>
 *   <li>{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getTestStep()
 * @model
 * @generated
 */
public interface TestStep extends EObject
{
  /**
   * Returns the value of the '<em><b>Object</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' attribute.
   * @see #setObject(String)
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getTestStep_Object()
   * @model
   * @generated
   */
  String getObject();

  /**
   * Sets the value of the '{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getObject <em>Object</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' attribute.
   * @see #getObject()
   * @generated
   */
  void setObject(String value);

  /**
   * Returns the value of the '<em><b>Predicate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate</em>' attribute.
   * @see #setPredicate(String)
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getTestStep_Predicate()
   * @model
   * @generated
   */
  String getPredicate();

  /**
   * Sets the value of the '{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getPredicate <em>Predicate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate</em>' attribute.
   * @see #getPredicate()
   * @generated
   */
  void setPredicate(String value);

  /**
   * Returns the value of the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' containment reference.
   * @see #setTable(Table)
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getTestStep_Table()
   * @model containment="true"
   * @generated
   */
  Table getTable();

  /**
   * Sets the value of the '{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getTable <em>Table</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' containment reference.
   * @see #getTable()
   * @generated
   */
  void setTable(Table value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference.
   * @see #setText(Text)
   * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getTestStep_Text()
   * @model containment="true"
   * @generated
   */
  Text getText();

  /**
   * Sets the value of the '{@link org.farhan.dsl.sheepdog.sheepDog.TestStep#getText <em>Text</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' containment reference.
   * @see #getText()
   * @generated
   */
  void setText(Text value);

} // TestStep
