/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.sheepdog.ui.quickfix;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.jface.text.BadLocationException;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.farhan.dsl.sheepdog.sheepDog.Cell;
import org.farhan.dsl.sheepdog.sheepDog.TestStep;
import org.farhan.dsl.sheepdog.sheepDog.TestStepContainer;
import org.farhan.dsl.sheepdog.sheepDog.TestSuite;
import org.farhan.dsl.issues.CellIssueResolver;
import org.farhan.dsl.issues.SheepDogIssueProposal;
import org.farhan.dsl.issues.TestStepIssueResolver;
import org.farhan.dsl.issues.TestSuiteIssueResolver;
import org.farhan.dsl.issues.TestStepContainerIssueResolver;
import org.farhan.dsl.sheepdog.generator.SheepDogGenerator;
import org.farhan.dsl.sheepdog.impl.CellImpl;
import org.farhan.dsl.sheepdog.impl.TestStepContainerImpl;
import org.farhan.dsl.sheepdog.impl.TestStepImpl;
import org.farhan.dsl.sheepdog.impl.TestSuiteImpl;
import org.farhan.dsl.sheepdog.validation.SheepDogValidator;

/**
 * Custom quickfixes.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class SheepDogQuickfixProvider extends DefaultQuickfixProvider {

	@Fix(SheepDogValidator.TEST_STEP_NAME_STEP_OBJECT_WORKSPACE)
	@Fix(SheepDogValidator.TEST_STEP_NAME_STEP_DEFINITION_WORKSPACE)
	@Fix(SheepDogValidator.ROW_CELL_LIST_WORKSPACE)
	public void fixTestStepReference(final Issue issue, IssueResolutionAcceptor acceptor) {

		acceptor.accept(issue, "Create definition", "Create a TestStep definition in the TestStep object", "upcase.png",
				new IModification() {
					public void apply(IModificationContext context) throws BadLocationException {
						Resource resource = new ResourceSetImpl().getResource(issue.getUriToProblem(), true);
						TestStep step = (TestStep) resource
								.getEObject(issue.getUriToProblem().toString().split("#")[1]);
						(new SheepDogGenerator()).doGenerate(step);
					}
				});

		Resource resource = new ResourceSetImpl().getResource(issue.getUriToProblem(), true);
		TestStep step = (TestStep) resource.getEObject(issue.getUriToProblem().toString().split("#")[1]);
		for (SheepDogIssueProposal p : TestStepIssueResolver.proposeNameWorkspace(new TestStepImpl(step))) {
			acceptor.accept(issue, p.getId(), p.getDescription(), "upcase.png", new IModification() {
				public void apply(IModificationContext context) throws BadLocationException {
					// TODO try issue.getLength
					context.getXtextDocument().replace(issue.getOffset(), step.getName().length(), p.getValue());
				}
			});
		}
	}

	@Fix(SheepDogValidator.TEST_STEP_CONTAINER_NAME_ONLY)
	public void fixTestStepContainerName(final Issue issue, IssueResolutionAcceptor acceptor) {
		// TODO get rid of upcase.png
		Resource resource = new ResourceSetImpl().getResource(issue.getUriToProblem(), true);
		TestStepContainer theTestStepContainer = (TestStepContainer) resource
				.getEObject(issue.getUriToProblem().toString().split("#")[1]);
		for (SheepDogIssueProposal p : TestStepContainerIssueResolver
				.proposeNameOnly(new TestStepContainerImpl(theTestStepContainer))) {
			acceptor.accept(issue, p.getId(), p.getDescription(), "upcase.png", new IModification() {
				public void apply(IModificationContext context) throws BadLocationException {
					// TODO try issue.getLength
					context.getXtextDocument().replace(issue.getOffset(), theTestStepContainer.getName().length(),
							p.getValue());
				}
			});
		}
	}

	@Fix(SheepDogValidator.TEST_SUITE_NAME_ONLY)
	public void fixTestSuiteName(final Issue issue, IssueResolutionAcceptor acceptor) {
		// TODO get rid of upcase.png
		Resource resource = new ResourceSetImpl().getResource(issue.getUriToProblem(), true);
		TestSuite theTestSuite = (TestSuite) resource.getEObject(issue.getUriToProblem().toString().split("#")[1]);
		for (SheepDogIssueProposal p : TestSuiteIssueResolver.proposeNameOnly(new TestSuiteImpl(theTestSuite))) {
			acceptor.accept(issue, p.getId(), p.getDescription(), "upcase.png", new IModification() {
				public void apply(IModificationContext context) throws BadLocationException {
					context.getXtextDocument().replace(issue.getOffset(), theTestSuite.getName().length(),
							p.getValue());
				}
			});
		}
	}

	@Fix(SheepDogValidator.CELL_NAME_ONLY)
	public void fixCellName(final Issue issue, IssueResolutionAcceptor acceptor) {

		Resource resource = new ResourceSetImpl().getResource(issue.getUriToProblem(), true);
		Cell theCell = (Cell) resource.getEObject(issue.getUriToProblem().toString().split("#")[1]);
		for (SheepDogIssueProposal p : CellIssueResolver.proposeNameOnly(new CellImpl(theCell))) {
			acceptor.accept(issue, p.getId(), p.getDescription(), "upcase.png", new IModification() {
				public void apply(IModificationContext context) throws BadLocationException {
					// TODO try issue.getLength
					context.getXtextDocument().replace(issue.getOffset(), theCell.getName().length(), p.getValue());
				}
			});
		}
	}

}
