/*
 * generated by Xtext 2.41.0
 */
package org.farhan.dsl.asciidoc.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAsciiDocScopeProvider extends DelegatingScopeProvider {
}
