/*
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.sheepdog.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSheepDogScopeProvider extends DelegatingScopeProvider {
}
