/*
 * generated by Xtext 2.38.0
 */
package org.farhan.dsl.sheepdog;

import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.eclipse.xtext.parser.IParser;
import org.eclipse.xtext.parser.antlr.Lexer;
import org.eclipse.xtext.parser.antlr.LexerBindings;
import org.eclipse.xtext.parser.antlr.LexerProvider;
import org.farhan.dsl.issues.LoggerFactory;
import org.farhan.dsl.lang.SheepDogFactory;
import org.farhan.dsl.sheepdog.generator.SheepDogOutputConfigurationProvider;
import org.farhan.dsl.sheepdog.impl.SheepDogFactoryImpl;
import org.farhan.dsl.sheepdog.impl.EclipseFileRepository;
import org.farhan.dsl.sheepdog.parser.antlr.SheepDogParser;
import org.farhan.dsl.sheepdog.parser.antlr.internal.InternalSheepDogLexer;
import org.farhan.dsl.sheepdog.parser.antlr.internal.SheepDogLexer;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.Singleton;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class SheepDogRuntimeModule extends AbstractSheepDogRuntimeModule {

	@Override
	public Class<? extends IParser> bindIParser() {
		return SheepDogParser.class;
	}

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(IOutputConfigurationProvider.class).to(SheepDogOutputConfigurationProvider.class)
				.in(Singleton.class);
		SheepDogFactory.instance = new SheepDogFactoryImpl(new EclipseFileRepository());
		LoggerFactory.setLoggerImplementation(new SheepDogLogger());
		
		//org.apache.log4j.Logger.getRootLogger().setLevel(org.apache.log4j.Level.DEBUG);
		//org.apache.log4j.BasicConfigurator.configure();
	}

	@Override
	public Class<? extends Lexer> bindLexer() {
		return SheepDogLexer.class;
	}

	@Override
	public Provider<? extends InternalSheepDogLexer> provideInternalSheepDogLexer() {
		return LexerProvider.create(SheepDogLexer.class);
	}

	@Override
	public void configureRuntimeLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerBindings.RUNTIME)).to(SheepDogLexer.class);
	}
}
