/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.sheepdog.ui.contentassist;

import java.io.File;
import org.apache.log4j.Logger;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.Path;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ConfigurableCompletionProposal;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.farhan.dsl.issues.*;
import org.farhan.dsl.lang.ITestProject;
import org.farhan.dsl.lang.SheepDogBuilder;
import org.farhan.dsl.lang.SheepDogFactory;
import org.farhan.dsl.sheepdog.impl.TestStepImpl;
import org.farhan.dsl.sheepdog.sheepDog.And;
import org.farhan.dsl.sheepdog.sheepDog.Given;
import org.farhan.dsl.sheepdog.sheepDog.TestStep;
import org.farhan.dsl.sheepdog.sheepDog.Then;
import org.farhan.dsl.sheepdog.sheepDog.When;

/**
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class SheepDogProposalProvider extends AbstractSheepDogProposalProvider {

	private static final Logger logger = Logger.getLogger(SheepDogProposalProvider.class);

	public void completeAnd_StepObjectName(And step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeAnd_StepObjectName(step, assignment, context, acceptor);
		completeStepObject(step, assignment, context, acceptor);
	}

	public void completeAnd_StepDefinitionName(And step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeAnd_StepDefinitionName(step, assignment, context, acceptor);
		completeStepDefinitionName(step, assignment, context, acceptor);
	}

	private void completeCellList(TestStep step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		logger.debug("Entering completeCellList for element: " + step.toString());
		try {
			initProject(step.eResource());
			for (SheepDogIssueProposal p : RowIssueResolver.suggestCellListWorkspace(new TestStepImpl(step))) {
				ConfigurableCompletionProposal proposal = (ConfigurableCompletionProposal) createCompletionProposal(
						p.getValue(), p.getId(), null, context);
				if (proposal != null) {
					proposal.setAdditionalProposalInfo(p.getDescription());
					acceptor.accept(proposal);
				}
			}
		} catch (Exception e) {
			logger.error("Failed in content assist for " + step.toString() + ": " + e.getMessage(), e);
		}
		logger.debug("Exiting completeCellList");
	}

	public void completeGiven_StepObjectName(Given step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeGiven_StepObjectName(step, assignment, context, acceptor);
		completeStepObject(step, assignment, context, acceptor);
	}

	public void completeGiven_StepDefinitionName(Given step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeGiven_StepDefinitionName(step, assignment, context, acceptor);
		completeStepDefinitionName(step, assignment, context, acceptor);
	}

	private void completeStepObject(TestStep step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		TestStepImpl testStep = new TestStepImpl(step);
		logger.debug("Entering completeObject for element: " + testStep.getName());
		try {
			initProject(step.eResource());
			for (SheepDogIssueProposal p : TestStepIssueResolver.suggestStepObjectNameWorkspace(testStep)) {
				ConfigurableCompletionProposal proposal = (ConfigurableCompletionProposal) createCompletionProposal(
						p.getValue(), p.getId(), null, context);
				if (proposal != null) {
					proposal.setAdditionalProposalInfo(p.getDescription());
					acceptor.accept(proposal);
				}
			}
		} catch (Exception e) {
			logger.error("Failed in content assist for " + testStep.getName() + ": " + e.getMessage(), e);
		}
		logger.debug("Exiting completeObject");
	}

	private void completeStepDefinitionName(TestStep step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		TestStepImpl testStep = new TestStepImpl(step);
		logger.debug("Entering completeStepDefinitionName for element: " + testStep.getName());
		try {
			initProject(step.eResource());
			for (SheepDogIssueProposal p : TestStepIssueResolver.suggestStepDefinitionNameWorkspace(testStep)) {
				ConfigurableCompletionProposal proposal = (ConfigurableCompletionProposal) createCompletionProposal(
						p.getValue(), p.getId(), null, context);
				if (proposal != null) {
					proposal.setAdditionalProposalInfo(p.getDescription());
					acceptor.accept(proposal);
				}
			}
		} catch (Exception e) {
			logger.error("Failed in content assist for " + testStep.getName() + ": " + e.getMessage(), e);
		}
		logger.debug("Exiting completeStepDefinitionName");
	}

	public void completeRow_CellList(EObject model, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeRow_CellList(model, assignment, context, acceptor);
		completeCellList((TestStep) model, assignment, context, acceptor);
	}

	public void completeThen_StepObjectName(Then step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeThen_StepObjectName(step, assignment, context, acceptor);
		completeStepObject(step, assignment, context, acceptor);
	}

	public void completeThen_StepDefinitionName(Then step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeThen_StepDefinitionName(step, assignment, context, acceptor);
		completeStepDefinitionName(step, assignment, context, acceptor);
	}

	public void completeWhen_StepObjectName(When step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeWhen_StepObjectName(step, assignment, context, acceptor);
		completeStepObject(step, assignment, context, acceptor);
	}

	public void completeWhen_StepDefinitionName(When step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeWhen_StepDefinitionName(step, assignment, context, acceptor);
		completeStepDefinitionName(step, assignment, context, acceptor);
	}

	private void initProject(Resource resource) {
		ITestProject parent = SheepDogBuilder.createTestProject();
		if (parent.getName() == null) {
			IFile resourceIFile = ResourcesPlugin.getWorkspace().getRoot()
					.getFile(new Path(resource.getURI().toPlatformString(true)));
			File resourceFile = new File(resourceIFile.getProject().getLocationURI());
			parent.setName(resourceFile.getAbsolutePath());
		}
	}

}
