/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.sheepdog.ui.contentassist;

import java.io.File;
import java.io.PrintWriter;
import java.io.StringWriter;
import org.apache.log4j.Logger;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.Path;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ConfigurableCompletionProposal;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.farhan.dsl.issues.*;
import org.farhan.dsl.lang.ITestProject;
import org.farhan.dsl.lang.SheepDogFactory;
import org.farhan.dsl.sheepdog.impl.TestStepImpl;
import org.farhan.dsl.sheepdog.sheepDog.And;
import org.farhan.dsl.sheepdog.sheepDog.Given;
import org.farhan.dsl.sheepdog.sheepDog.TestStep;
import org.farhan.dsl.sheepdog.sheepDog.Then;
import org.farhan.dsl.sheepdog.sheepDog.When;

/**
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class SheepDogProposalProvider extends AbstractSheepDogProposalProvider {

	private static final Logger logger = Logger.getLogger(SheepDogProposalProvider.class);

	public void completeAnd_Name(And step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeAnd_Name(step, assignment, context, acceptor);
		completeName(step, assignment, context, acceptor);
	}

	private void completeCellList(TestStep step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		try {
			initProject(step.eResource());
			for (SheepDogIssueProposal p : RowIssueResolver.suggestCellListWorkspace(new TestStepImpl(step))) {
				ConfigurableCompletionProposal proposal = (ConfigurableCompletionProposal) createCompletionProposal(
						p.getValue(), p.getId(), null, context);
				if (proposal != null) {
					proposal.setAdditionalProposalInfo(p.getDescription());
					acceptor.accept(proposal);
				}
			}
		} catch (Exception e) {
			logError(e, "");
		}
	}

	public void completeGiven_Name(Given step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeGiven_Name(step, assignment, context, acceptor);
		completeName(step, assignment, context, acceptor);
	}

	private void completeName(TestStep step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		try {
			initProject(step.eResource());
			for (SheepDogIssueProposal p : TestStepIssueResolver.suggestNameObjectWorkspace(new TestStepImpl(step))) {
				ConfigurableCompletionProposal proposal = (ConfigurableCompletionProposal) createCompletionProposal(
						p.getValue(), p.getId(), null, context);
				if (proposal != null) {
					proposal.setAdditionalProposalInfo(p.getDescription());
					acceptor.accept(proposal);
				}
			}
			for (SheepDogIssueProposal p : TestStepIssueResolver
					.suggestNamePredicateWorkspace(new TestStepImpl(step))) {
				ConfigurableCompletionProposal proposal = (ConfigurableCompletionProposal) createCompletionProposal(
						p.getValue(), p.getId(), null, context);
				if (proposal != null) {
					proposal.setAdditionalProposalInfo(p.getDescription());
					acceptor.accept(proposal);
				}
			}
		} catch (Exception e) {
			// TODO replace with utility to combine both
			logError(e, step.getName().getObject() + step.getName().getPredicate());
		}
	}

	public void completeRow_CellList(EObject model, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeRow_CellList(model, assignment, context, acceptor);
		completeCellList((TestStep) model, assignment, context, acceptor);
	}

	public void completeThen_Name(Then step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeThen_Name(step, assignment, context, acceptor);
		completeName(step, assignment, context, acceptor);
	}

	public void completeWhen_Name(When step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeWhen_Name(step, assignment, context, acceptor);
		completeName(step, assignment, context, acceptor);
	}

	private void logError(Exception e, String name) {
		logger.error("There was a problem for step: " + name);
		StringWriter sw = new StringWriter();
		e.printStackTrace(new PrintWriter(sw));
		logger.error(sw.toString());
	}

	private void initProject(Resource resource) {
		ITestProject parent = SheepDogFactory.instance.createTestProject();
		if (parent.getName() == null) {
			IFile resourceIFile = ResourcesPlugin.getWorkspace().getRoot()
					.getFile(new Path(resource.getURI().toPlatformString(true)));
			File resourceFile = new File(resourceIFile.getProject().getLocationURI());
			parent.setName(resourceFile.getAbsolutePath());
		}
	}
}
