/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.sheepdog.ui.contentassist;

import java.io.PrintWriter;
import java.io.StringWriter;
import org.apache.log4j.Logger;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ConfigurableCompletionProposal;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.farhan.dsl.lang.*;
import org.farhan.dsl.issues.*;
import org.farhan.dsl.sheepdog.impl.RowImpl;
import org.farhan.dsl.sheepdog.impl.SourceFileRepository;
import org.farhan.dsl.sheepdog.impl.TestProjectImpl;
import org.farhan.dsl.sheepdog.impl.TestStepImpl;
import org.farhan.dsl.sheepdog.sheepDog.And;
import org.farhan.dsl.sheepdog.sheepDog.Given;
import org.farhan.dsl.sheepdog.sheepDog.Row;
import org.farhan.dsl.sheepdog.sheepDog.TestStep;
import org.farhan.dsl.sheepdog.sheepDog.Then;
import org.farhan.dsl.sheepdog.sheepDog.When;

/**
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class SheepDogProposalProvider extends AbstractSheepDogProposalProvider {

	private static final Logger logger = Logger.getLogger(SheepDogProposalProvider.class);

	public void completeAnd_Name(And step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeAnd_Name(step, assignment, context, acceptor);
		completeName(step, assignment, context, acceptor);
	}

	public void completeGiven_Name(Given step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeGiven_Name(step, assignment, context, acceptor);
		completeName(step, assignment, context, acceptor);
	}

	private void completeName(TestStep step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		try {
			ITestProject testProject = new TestProjectImpl(
					new SourceFileRepository(step.eResource().getURI().toPlatformString(true)));
			ITestStep iTestStep = new TestStepImpl(step);
			iTestStep.getParent().getParent().setParent(testProject);
			for (SheepDogIssueProposal p : TestStepIssueResolver.proposeName(iTestStep, testProject)) {
				ConfigurableCompletionProposal proposal = (ConfigurableCompletionProposal) createCompletionProposal(
						p.getValue(), p.getId(), null, context);
				if (proposal != null) {
					proposal.setAdditionalProposalInfo(p.getDescription());
					acceptor.accept(proposal);
				}
			}
		} catch (Exception e) {
			logError(e, step.getName());
		}
	}

	public void completeRow_CellList(Row row, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		// TODO confirm the first arg is a Row
		try {
			for (SheepDogIssueProposal p : RowIssueResolver.proposeCellList(new RowImpl(row))) {
				ConfigurableCompletionProposal proposal = (ConfigurableCompletionProposal) createCompletionProposal(
						p.getValue(), p.getId(), null, context);
				if (proposal != null) {
					proposal.setAdditionalProposalInfo(p.getDescription());
					acceptor.accept(proposal);
				}
			}
		} catch (Exception e) {
			logError(e, "");
		}
	}

	public void completeThen_Name(Then step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeThen_Name(step, assignment, context, acceptor);
		completeName(step, assignment, context, acceptor);
	}

	public void completeWhen_Name(When step, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeWhen_Name(step, assignment, context, acceptor);
		completeName(step, assignment, context, acceptor);
	}

	private void logError(Exception e, String name) {
		logger.error("There was an error listing proposals for: " + name);
		StringWriter sw = new StringWriter();
		e.printStackTrace(new PrintWriter(sw));
		logger.error(sw.toString());
	}
}
