/*
 * generated by Xtext 2.41.0
 */
package org.farhan.dsl.cucumber.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCucumberValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.farhan.dsl.cucumber.cucumber.CucumberPackage.eINSTANCE);
		return result;
	}
}
