/**
 * generated by Xtext 2.39.0
 */
package org.xtext.example.mydsl.generator;

import com.google.common.collect.Iterators;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.myDsl.Greeting;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    Iterable<Greeting> _iterable = IteratorExtensions.<Greeting>toIterable(Iterators.<Greeting>filter(resource.getAllContents(), Greeting.class));
    for (final Greeting greeting : _iterable) {
      {
        final String className = greeting.getName().replace(" ", "");
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("// Generated from ");
        String _lastSegment = resource.getURI().lastSegment();
        _builder.append(_lastSegment);
        _builder.newLineIfNotEmpty();
        _builder.append("public class ");
        _builder.append(className);
        _builder.append("Greeter {");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public static void main(String[] args) {");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("System.out.println(\"Hello ");
        String _name = greeting.getName();
        _builder.append(_name, "\t\t");
        _builder.append("!\");");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public String getGreeting() {");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("return \"Hello ");
        String _name_1 = greeting.getName();
        _builder.append(_name_1, "\t\t");
        _builder.append("!\";");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        fsa.generateFile((className + "Greeter.java"), _builder);
      }
    }
  }
}
