/*
 * generated by Xtext 2.42.0
 */
package org.farhan.dsl.asciidoc.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AsciiDocAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/farhan/dsl/asciidoc/parser/antlr/internal/InternalAsciiDoc.tokens");
	}
}
